# Generated by Django 5.2.17 on 2026-09-23 19:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='Ferramenta')),
                ('url', models.URLField(validators=[django.core.validators.URLValidator(schemes=['https', 'http'])], verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Descrição')),
                ('published', models.BooleanField(default=False, verbose_name='Visível ao cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='external_links_externallink_tenant_id')],
            },
        ),
    ]
