# Generated by Django 5.2.17 on 2026-09-23 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('attribute_keys', models.JSONField(blank=True, default=list, verbose_name='Atributos permitidos')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, verbose_name='Recurso')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('partial', 'Parcial'), ('inactive', 'Inativo')], default='active', max_length=16, verbose_name='Situação')),
                ('description', models.TextField(blank=True, verbose_name='Descrição técnica')),
                ('capacity_gbps', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Capacidade (Gbps)')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Atributos específicos (JSON)')),
                ('source', models.CharField(default='Consultoria — registro manual', max_length=150, verbose_name='Fonte')),
                ('observed_at', models.DateTimeField(verbose_name='Data da verificação')),
                ('published', models.BooleanField(default=False, verbose_name='Visível ao cliente')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.resourcetype', verbose_name='Tipo')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='inventory_resource_tenant_id')],
            },
        ),
    ]
