# Generated by Django 5.2.17 on 2026-09-23 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Marco de evolução')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('occurred_on', models.DateField(verbose_name='Data')),
                ('published', models.BooleanField(default=False, verbose_name='Visível ao cliente')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recommendations.recommendation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='timeline_event_tenant_id')],
            },
        ),
    ]
