# Generated by Django 5.2.17 on 2026-09-23 19:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Métrica')),
                ('unit', models.CharField(max_length=40, verbose_name='Unidade')),
            ],
        ),
        migrations.CreateModel(
            name='MetricObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('observed_at', models.DateTimeField(verbose_name='Data da observação')),
                ('source', models.CharField(default='Registro manual', max_length=180, verbose_name='Fonte')),
                ('assumptions', models.TextField(blank=True, verbose_name='Premissas e contexto')),
                ('estimated', models.BooleanField(default=False, verbose_name='Estimativa')),
                ('published', models.BooleanField(default=False, verbose_name='Visível ao cliente')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metrics.metricdefinition', verbose_name='Métrica')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-observed_at', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'definition', 'observed_at'], name='metrics_met_tenant__153657_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='metrics_metricobservation_tenant_id')],
            },
        ),
    ]
