# Generated by Django 5.2.17 on 2026-09-23 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('risks', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180, verbose_name='Melhoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('na', 'Não aplicável'), ('identified', 'Identificado'), ('recommended', 'Recomendado'), ('planned', 'Planejado'), ('in_progress', 'Em andamento'), ('done', 'Concluído'), ('blocked', 'Bloqueado')], default='recommended', max_length=20, verbose_name='Estado')),
                ('justification', models.TextField(verbose_name='Justificativa')),
                ('impact', models.TextField(blank=True, verbose_name='Impacto esperado')),
                ('effort', models.CharField(blank=True, max_length=120, verbose_name='Esforço estimado')),
                ('owner', models.CharField(blank=True, max_length=160, verbose_name='Responsável')),
                ('recommended_on', models.DateField(blank=True, null=True, verbose_name='Data recomendada')),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('block_reason', models.TextField(blank=True, verbose_name='Motivo do bloqueio manual')),
                ('client_notes', models.TextField(blank=True, verbose_name='Observações para o cliente')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('editorial_status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em revisão'), ('published', 'Publicado')], default='draft', max_length=12, verbose_name='Publicação')),
                ('source', models.CharField(default='Consultor', max_length=100, verbose_name='Origem')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessmentcategory', verbose_name='Área')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependents', to='recommendations.recommendation')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependencies', to='recommendations.recommendation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendationRisk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommendations.recommendation')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risks.risk')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoadmapPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horizon', models.CharField(choices=[('now', 'Agora'), ('next', 'A seguir'), ('later', 'Futuro')], default='next', max_length=20, verbose_name='Horizonte')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Previsão')),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='placement', to='recommendations.recommendation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='recommendations_recommendation_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='recommendationdependency',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='recommendations_recommendationdependency_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='recommendationdependency',
            constraint=models.UniqueConstraint(fields=('recommendation', 'prerequisite'), name='unique_dependency'),
        ),
        migrations.AddConstraint(
            model_name='recommendationdependency',
            constraint=models.CheckConstraint(condition=models.Q(('recommendation', models.F('prerequisite')), _negated=True), name='no_self_dependency'),
        ),
        migrations.AddConstraint(
            model_name='recommendationrisk',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='recommendations_recommendationrisk_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='recommendationrisk',
            constraint=models.UniqueConstraint(fields=('recommendation', 'risk'), name='unique_recommendation_risk'),
        ),
        migrations.AddConstraint(
            model_name='roadmapplacement',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='recommendations_roadmapplacement_tenant_id'),
        ),
    ]
