# Generated by Django 5.2.17 on 2026-09-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
