# Generated by Django 5.2.17 on 2026-10-06 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('tenancy', '0003_preserve_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='Título')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='assessments.assessment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'Consultor'), ('assistant', 'IA'), ('tool', 'Ação executada')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('tool_name', models.CharField(blank=True, max_length=60)),
                ('tool_args', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assist.aiconversation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='aiconversation',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='ai_assist_aiconversation_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='aimessage',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='ai_assist_aimessage_tenant_id'),
        ),
    ]
