#!/bin/sh
set -eu
psql --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set=ON_ERROR_STOP=1 --set=runtime_password="$DB_APP_PASSWORD" <<'SQL'
CREATE ROLE isp_app LOGIN PASSWORD :'runtime_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT CONNECT ON DATABASE isp_panel TO isp_app;
GRANT USAGE ON SCHEMA public TO isp_app;
ALTER DEFAULT PRIVILEGES FOR ROLE isp_owner IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO isp_app;
ALTER DEFAULT PRIVILEGES FOR ROLE isp_owner IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO isp_app;
SQL
