# Generated by Django 5.2.17 on 2026-09-23 19:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Área')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MaturityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nível')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='Ordem')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('assessed_on', models.DateField(verbose_name='Data da avaliação')),
                ('summary', models.TextField(blank=True, verbose_name='Resumo para o cliente')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessmenttemplateversion', verbose_name='Metodologia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Critério')),
                ('guidance', models.TextField(blank=True, verbose_name='Orientação')),
                ('weight', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Peso')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessmentcategory', verbose_name='Área')),
            ],
        ),
        migrations.CreateModel(
            name='MaturityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessmentitemdefinition', verbose_name='Critério obrigatório')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.maturitylevel', verbose_name='Nível')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_key', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('met', 'Atendido'), ('partial', 'Parcialmente atendido'), ('unmet', 'Não atendido'), ('na', 'Não aplicável')], max_length=10, verbose_name='Situação')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário técnico / justificativa')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Observação interna')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='assessments.assessment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='assessments_assessmentanswer_tenant_id'), models.UniqueConstraint(fields=('assessment', 'item_key'), name='unique_assessment_answer')],
            },
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('tenant', 'id'), name='assessments_assessment_tenant_id'),
        ),
        migrations.AddConstraint(
            model_name='maturityrule',
            constraint=models.UniqueConstraint(fields=('level', 'item'), name='unique_level_rule'),
        ),
    ]
