# Generated by Django 5.2.17 on 2026-09-23 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=200, verbose_name='Razão social')),
                ('trade_name', models.CharField(max_length=160, verbose_name='Nome fantasia')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='Região de operação')),
                ('joined_on', models.DateField(verbose_name='Início da assessoria')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='clients_client_tenant_id'), models.UniqueConstraint(fields=('tenant',), name='one_client_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='Função')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='clients_clientcontact_tenant_id')],
            },
        ),
    ]
