# Generated by Django 5.2.17 on 2026-09-23 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180, verbose_name='Risco')),
                ('severity', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], default='medium', max_length=12, verbose_name='Severidade')),
                ('description', models.TextField(verbose_name='Consequência e justificativa')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('mitigated', 'Mitigado'), ('accepted', 'Aceito')], default='open', max_length=12, verbose_name='Situação')),
                ('owner', models.CharField(blank=True, max_length=160, verbose_name='Responsável')),
                ('published', models.BooleanField(default=False, verbose_name='Visível ao cliente')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Observações internas')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'id'), name='risks_risk_tenant_id')],
            },
        ),
    ]
