# Generated by Django 5.2.17 on 2026-10-02 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_preserve_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system', models.CharField(default='netbackup', max_length=40)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('success', 'Sucesso'), ('partial_failure', 'Falha parcial'), ('failed', 'Falha')], default='running', max_length=20)),
                ('tenants_considered', models.PositiveIntegerField(default=0)),
                ('tenants_matched', models.PositiveIntegerField(default=0)),
                ('tenants_succeeded', models.PositiveIntegerField(default=0)),
                ('tenants_failed', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalObjectMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system', models.CharField(default='netbackup', max_length=40)),
                ('external_id', models.CharField(max_length=200, verbose_name='Identificador externo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('system', 'external_id'), name='unique_external_mapping'), models.UniqueConstraint(fields=('system', 'tenant'), name='one_mapping_per_system_per_tenant')],
            },
        ),
    ]
